lab0:first commit
vanya-9/OOP pull request #1
Opened 2024-09-18 12:28 UTC by vanya-9

2024-09-18 13:37 UTC, danillo19 requested changes

2024-09-18 13:37 UTC, danillo19 commented on lab0/b/src/writing.cpp
> +    std::ofstream out("csv.txt", std::ios::app);
Если файл не удалось открыть, то хорошо бы об этом узнать, надо хотя бы вывести в консоль информацию об этом. Есть функция fail у стрима: https://en.cppreference.com/w/cpp/io/basic_ios/fail.
В доке есть пример как обработать ошибку и во время работы с файлом( в доке чтение) и при создание, write мог бы вернуть статус ошибки и в main уже человеко-читаемо статус обработать по типу:

```
int write(std::output_filename) {
    std::ofstream out(output_filename);
    if (!out) {
        return FAILED_TO_OPEN; // твой кастомный код ошибки
    }
    ...
}
```

2024-09-18 13:37 UTC, danillo19 commented on lab0/b/src/creating_map.cpp
> +        {
тоже форматирование в соответствие с гайдом:
https://google.github.io/styleguide/cppguide.html#Formatting_Looping_Branching

2024-09-18 13:37 UTC, danillo19 commented on lab0/b/src/creating_map.cpp
> +void create_map(std::string file_name, std::map<std::string, unsigned> &words, double* k)
строку лучше передавать по ссылке

2024-09-18 13:37 UTC, danillo19 commented on lab0/b/src/creating_map.cpp
> +    while (getline(shows_file, read))
Вынеси добавление в мапу в отдельную функцию, код дублируется. Дополнительно можно цикл чтения переписать вот с таким хаком, и код получше читается.
```
while (getline(shows_file, read)) {
        // Тут добавляем \n в конце строки, чтобы сработал process_word
        read += ' ';  // or any other non-symbol character based on check_symbol

        for (char c : read) {
            if (check_symbol(c)) {
                new_word += c;
            } else {
                process_word(new_word, words, k); // функция добавления в мапу
            }
        }
    }
    ```

2024-09-19 07:35 UTC, vanya-9 commented on lab0/b/src/main.cpp
> +    double k = 0.0;                 // количество слов в файле
обозвал

2024-09-19 07:43 UTC, vanya-9 commented on lab0/b/src/creating_map.cpp
> +void create_map(std::string file_name, std::map<std::string, unsigned> &words, double* k)
переделал

2024-09-19 07:44 UTC, vanya-9 commented on lab0/b/src/creating_map.cpp
> +    while (getline(shows_file, read))
вынес отдельно

2024-09-19 07:46 UTC, vanya-9 commented on lab0/b/src/creating_map.cpp
> +bool check_symbol(char symbol)
переделал

2024-09-19 07:47 UTC, vanya-9 commented on lab0/b/src/creating_map.cpp
> +    if (std::isalpha(symbol) || std::isdigit(symbol))
сделал

2024-09-19 07:55 UTC, vanya-9 commented on lab0/b/src/main.cpp
> +#include "creating_map.h"
вроде как подрубил

2024-09-22 16:14 UTC, danillo19 requested changes
Как то сложно декомпозировал на классы, то что выделяешь базовые вещи в маленькие функции это круто, но их лучше либо выносить как отдельные функции, а не методы, или если че то простое пишешь, то можно и не выносить, это и так понятно.

2024-09-22 16:14 UTC, danillo19 commented on lab0/b/src/writing_csv.cpp
> +  std::ofstream out("csv.txt", std::ios::app);
Тут хардкодишь файл, в который собираешься писать. Нужно сделать класс по типу Writer и там функцию writeCSV и туда передать название файла и данные

2024-09-22 16:14 UTC, danillo19 commented on lab0/b/src/reading_file.cpp
> +void reading_file::improve_number_map(std::string new_word) {
лучше назвать increse_word_count

2024-09-22 16:14 UTC, danillo19 commented on lab0/b/src/reading_file.cpp
> +void reading_file::plus_word() { number_words++; }
Хоть и простые функции, но сходу тяжело читать, лучше это нормально расскрыть, хоть и строк больше займет

2024-09-22 16:14 UTC, danillo19 commented on lab0/b/src/main.cpp
> +  myfile.set_file_name();
прочитай файл из argv

2024-09-22 16:14 UTC, danillo19 commented on lab0/b/src/main.cpp
> +  vector_map.vector_sort(vector_map.get_vector_begin(),
как выше писал, лучше std::sort

2024-09-24 19:07 UTC, danillo19 requested changes

2024-09-25 12:04 UTC, vanya-9 commented
поправил

2024-09-26 11:20 UTC, danillo19 requested changes

2024-09-26 11:20 UTC, danillo19 commented on lab0/b/src/data_processing.h
> +class data_processing {
классы лучше называть с большой буквы и в camelCase

2024-09-26 11:20 UTC, danillo19 commented on lab0/b/src/main.cpp
> +    new_word.clear();
зачем очищать слово в addToMap? Нелогичное поведение

2024-09-26 11:20 UTC, danillo19 commented on lab0/b/src/main.cpp
> +  writing_file.Write(vector_map, map.GetNumberWords(), output_file);
раздели логические блоки кода пустой строкой, код одним куском тяжело читать

2024-09-26 11:20 UTC, danillo19 commented on lab0/b/src/writing_csv.h
> +class WriteCsv {
класс надо называть как существительные, writeCsv про функцию скорее + лучше назвать класс writer и внутри него writeCsv. Мало ли в будущем будет писать в txt, pdf и тд

2024-09-26 11:20 UTC, danillo19 commented on lab0/b/src/writing_csv.cpp
> +    out.close();
разделяй блоки, вот так намного лучше читается
```
void WriteCsv::Write(std::vector<std::pair<std::string, unsigned>> vector_map,
                     double number_words,
                     std::string output_file_name) {
                     
  SetFileName(output_file_name);
  std::ofstream out(file_writing_name_, std::ios::app);
  
  if (out.is_open()) {
    for (int i = 0; i < vector_map.size(); i++) {
      out << vector_map[i].first << " " << vector_map[i].second << " "
          << (vector_map[i].second / number_words) * kPercent << std::endl;
    }
    
    out.close();
}
```

2024-09-26 11:20 UTC, danillo19 commented on lab0/b/src/data_processing.cpp
> +              return element_one.second > element_two.second;
в лабе надо не только по частоте сортировать, но и по алфавиту, если частота совпадает

2024-09-26 11:20 UTC, danillo19 commented on lab0/b/src/main.cpp
> +  }
отдели while от инициализации переменных

2024-09-26 14:02 UTC, vanya-9 commented on lab0/b/src/data_processing.h
> +class data_processing {
да, все поправил, а этот пропустил)
исправил

2024-09-26 14:03 UTC, vanya-9 commented on lab0/b/src/main.cpp
> +    new_word.clear();
Написал отдельно

2024-09-26 14:04 UTC, vanya-9 commented on lab0/b/src/main.cpp
> +  writing_file.Write(vector_map, map.GetNumberWords(), output_file);
разделил

2024-09-26 14:09 UTC, vanya-9 commented on lab0/b/src/writing_csv.h
> +class WriteCsv {
назвал

2024-09-26 14:12 UTC, vanya-9 commented on lab0/b/src/writing_csv.cpp
> +    out.close();
поправил

2024-09-26 14:12 UTC, vanya-9 commented on lab0/b/src/main.cpp
> +  }
отделил

2024-09-27 04:12 UTC, danillo19 requested changes

2024-09-27 04:12 UTC, danillo19 commented on lab0/b/src/data_processing.cpp
> +  vector_map.assign(words.begin(), words.end());
сортировка сложных структур/классов быстрее через std::list

2024-09-27 04:12 UTC, danillo19 commented on lab0/b/src/writer.cpp
> +  std::ofstream out(file_writing_name_, std::ios::app);
форматирование

2024-09-27 04:12 UTC, danillo19 commented on lab0/b/src/reading_file.h
> +  std::string GetFileName();
в чем суть класса readingFile, если он просто оборачивает имя файла? Положи туда стрим тогда и в конструкторе его открой, сделай метод чтения из стрима в этом классе и, например, в деструкторе закрой. Сейчас нет закрытия input стрима

2024-09-27 04:12 UTC, danillo19 commented on lab0/b/src/writer.h
> +};
С writer аналогичная проблема как и у reader, внутри можно завести поле стрима и где то закрыть.

2024-09-27 04:12 UTC, danillo19 commented on lab0/b/src/main.cpp
> +void CreateMap(readingFile& input_file, dataProcessing& map) {
че то объектный подход потерялся, у тебя сейчас класс dataProcessing инкапсулирует логику подсчета, если так сделал, перенести туда этот метод и AddToMap например. IsDelimiter можно оставить как есть. Еще бы переназвать его, по типу CountFrequency или CalcWordsFrequency.

2024-09-27 04:12 UTC, danillo19 commented on lab0/b/src/data_processing.h
> +class dataProcessing {
класс с большой буквы

2024-09-27 04:12 UTC, danillo19 commented on lab0/b/src/data_processing.cpp
> +  words[word]++;
если везде ставишь _ в полях класса, то и для word сделай

2024-09-27 10:41 UTC, vanya-9 commented on lab0/b/src/writer.cpp
> +  std::ofstream out(file_writing_name_, std::ios::app);
отступ, всмысле?

2024-09-29 19:55 UTC, danillo19 approved these changes

2024-09-29 19:55 UTC, danillo19 commented on lab0/b/src/main.cpp
> +bool CountFrequency(char symbol) {
Было же ок все тут, IsDelimiter -> CountFrequency?)

2024-10-17 14:58 UTC, merged