Lab1
vanya-9/OOP pull request #2
Opened 2024-10-09 20:06 UTC by vanya-9

2024-10-12 08:51 UTC, danillo19 requested changes

2024-10-12 08:51 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +      return 0;
странно, что в методе получения размера у тебя в буфере что-то меняется

2024-10-12 08:51 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +      linearize_buffer[i] = buffer_[(head_ + i) % capacity_];
выделять новую память в данном случае плохая идея, тебе надо именно сдвинуть твой [head,...,tail] в начало buffer, т.е прокрутить массив до 0 элемента

2024-10-12 08:51 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +    tail_ = size();
тоже самое, что и с linearize, надо именно сдвинуть

2024-10-12 08:51 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +  }
вообще лучше вместо массива char использовать ```std::vectror<char>```, у тебя там и методы resize() есть, который ты можешь использовать, и при изменении capacity тебе не надо каждый раз делать аллокацию/деалокацию памяти. В линеаризации можешь вернуть ```std::vector<char>.data()```, он тебе кусок raw памяти вернет:
https://en.cppreference.com/w/cpp/container/vector/data

2024-10-12 08:51 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +  }
лучше переделать на 
```
if() {...; 
return;
}

//код в else

```

2024-10-12 08:51 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +  return *this;
с вектором можно будет сделать так:
```
buffer_ = cb.buffer;
head_ = cb.head_;
tail_ = cb.tail_;
```

2024-10-12 08:51 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +    buffer_[(tail_ - 1 + capacity_) % capacity_] = item;
вынести бы tail_ - 1 + capacity_ и head_ - 1 + capacity_ в методы по типу increment/decrement или moveHead/moveTail 
И (tail_ - 1 + capacity_) % capacity_ вынести в какой нибудь метод по типу getPos/getPosition

2024-10-12 08:51 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +}
кажется тут надо прямо очистить память и capacity в 0 проставить

2024-10-12 08:51 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +      buffer_[i] = '\0';
кажется надо использовать head_ в цикле, чтобы занулить нужные значения.
Доп к этому вынеси установку `\0` в функцию reset. Это для того, чтобы например в будущем легче было переписать или расширить твой буфер с сhar на что-то другое

2024-10-12 08:51 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +  }
как то сложно метод выглядит, нужно же просто передвинуть элементы так, чтобы дыру между first и last закрыть, если first и last покрывают весь буффер, делаешь clear, иначе делаешь сдвиг элементов с last по size в first и перекидываешь tail

2024-10-12 08:51 UTC, danillo19 commented on lab1/CircularBuffer_tets.cpp
> +TEST(CircularBufferTest, OperatorMas) {
Лучше назвать OperatorGetByIndex тогда уж

2024-10-12 13:06 UTC, vanya-9 commented on lab1/CircularBuffer.cpp
> +  }
Да, просто код переделался, изначально не так было, поправил

2024-10-12 13:07 UTC, vanya-9 commented on lab1/CircularBuffer.cpp
> +  }
поправил

2024-10-12 13:07 UTC, vanya-9 commented on lab1/CircularBuffer.cpp
> +};
поправил

2024-10-12 13:08 UTC, vanya-9 commented on lab1/CircularBuffer.cpp
> +      return 0;
Вроде только проверяется, не понял о чем речь

2024-10-12 14:07 UTC, vanya-9 commented on lab1/CircularBuffer.cpp
> +    tail_ = size();
поправил

2024-10-13 06:49 UTC, vanya-9 commented on lab1/CircularBuffer.cpp
> +    buffer_[(tail_ - 1 + capacity_) % capacity_] = item;
вынес только в increment  без getpos,а то они совпадать будут

2024-10-15 12:52 UTC, danillo19 requested changes

2024-10-15 12:52 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +    return ((tail_ - head_ + capacity_) % capacity_);
даже если в теле if одна строка, лучше обернуть, вообще лучше это переписать на if, else if, else

2024-10-15 12:52 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +      int fact_index = (head_ + i) % capacity_;
лучше назвать сurr_index, как current

2024-10-15 12:52 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +}
лучше инвертировать if, типо сделать if() {return} и дальше тело функции, так лучше код читается и понимается

2024-10-15 12:52 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +  }
а зачем return?

2024-10-15 12:52 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +  }
тоже инвертируй if
```
if (this == &cb) {
  return *this;
}

...
```
выглядит и читается намного лучше

2024-10-15 12:52 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +  tail_ = (tail_ + 1) % capacity_;
отдели if пустой строкой

2024-10-15 12:52 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +}
можно сделать без else:
```
if (full()) {
...
return
}

//код из else
```

2024-10-15 12:52 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +};
отделяй логические блоки пустой строкой

2024-10-15 12:52 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +  buffer_[insert_pos] = item;
а зачем insert_pos меняется так далеко от
```
buffer_[insert_pos] = item;
```

в цикле же ни head_, ни pos, ни capacity_ не меняются

2024-10-15 12:52 UTC, danillo19 commented on lab1/CircularBuffer.cpp
> +  tail_ = (tail_ - num_to_erase + capacity_) % capacity_;
разделяй блоки. кто-такой b? давай осмысленное нахвание переменной

2024-10-17 08:15 UTC, vanya-9 commented on lab1/CircularBuffer.cpp
> +  buffer_[insert_pos] = item;
на size повлияет

2024-10-24 23:48 UTC, danillo19 approved these changes

2024-12-12 19:38 UTC, merged